#ifndef PROJETO_PPP_FICHEIROS_CONSTANTES_H
#define PROJETO_PPP_FICHEIROS_CONSTANTES_H

#endif

#define MAX_STRING 100
#define MAX_STRING_DOUBLE 12

#define ERRO_GERAL -100
#define ERRO_ESPACO -101
#define ERRO_CONVERCAO -102
#define ERRO_FICHEIRO -103
#define ERRO_PROGRAMA -104
#define ERRO_NAO_ENCONTRADO -105
